# -*- coding: utf-8 -*-
"""Vlink_Q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MS8uj90zKpiRvxIa8exJsUHv_OTBW2v5
"""

def char_count(str):
     upper_ctr, lower_ctr, nber_ctr, special_ctr = 0, 0, 0, 0
     for i in range(len(str)):
          if str[i] >= 'A' and str[i] <= 'Z': upper_ctr += 1
          elif str[i] >= 'a' and str[i] <= 'z': lower_ctr += 1
          elif str[i] >= '0' and str[i] <= '9': nber_ctr += 1
          else: special_ctr += 1
     return upper_ctr, lower_ctr, nber_ctr, special_ctr

n = int(input("Enter length of String:"))

passw  = input("Enter Password:")
u, l, n, s = char_count(passw)
print('\nUpper case characters: ',u)
print('Lower case characters: ',l)
print('numbers: ',n)
print('Special case characters: ',s)
if(n<8):
    print((8 - n)," more characters should be added" )
else:
    print("Strong password")